### PR TITLE
Added DP & Some Algorithms which i practised for placements drives

### PR DESCRIPTION
**Pull request by VyavahareSiddesh**
Please review and add this to repo
AddedDP and algos .

### CODE REVIEW

**Comment by priyanka25081999** [comment]
> Please review and add this to repo
> AddedDP and algos .

**Comment by priyanka25081999** [comment]
Hello 

Please add output steps. Because, when a programmer runs your program, It is very difficult to know what should be entered in the output screen. So, please make the program interactive. 

Thanks for your contribution!!

**Comment by VyavahareSiddesh** [comment]
Now added the comments so user can understand the code well..

**Comment by priyanka25081999** [comment]
Ok great
Send me pull request again

**Pull request closed without merging**
